CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS household_db;
CREATE DATABASE IF NOT EXISTS expense_db;
CREATE DATABASE IF NOT EXISTS settlement_db;
CREATE DATABASE IF NOT EXISTS email_db;
